version: "3"
services:
  mariadb:
    container_name: 'mariadb_admin'
    image: 'bitnami/mariadb:latest'
    restart: always
    volumes:
      - ./mariadb:/bitnami/mariadb
      - ./conf/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:rw
      - ./conf/my.cnf:/opt/bitnami/mariadb/conf/my.cnf:rw
    environment:
      - BITNAMI_DEBUG=true
      - MARIADB_REPLICATION_MODE=######
      - MARIADB_REPLICATION_USER=######
      - MARIADB_REPLICATION_PASSWORD=######
      - MARIADB_USER=######
      - MARIADB_PASSWORD=######
      - MARIADB_DATABASE=######
      - MARIADB_ROOT_PASSWORD=######
      - MARIADB_SKIP_TEST_DB=yes
    ports:
      - 57.128.86.143:3306:3306 #External network
      - 10.0.2.143:3306:3306 #Internal network
volumes:
  mariadb:
    driver: local
networks:
  default:
    name: coolturate_network

